### ISSUE TITLE
[1.12.2] Add fluids first and fluid packet config from 1.7.10

### ISSUE THREAD

**Issue by Synthitic** [GlodBlock/AE2FluidCraft-Rework#45]
~~AE2FC version: 2.3.4R
PAE2 version: 0.52.2~~

~~Steps to reproduce:
Take drops of water or whatever, insert them into a fluid packet decoder that is connected to a network with fluid storage.~~

~~Expected behavior:
Turns the drops of liquid into its liquid form in the network.~~

~~Actual behavior:
The drops remain in the fluid packet decoder and do not turn into liquid.~~

**Add the fluids first and fluid packet config to 1.12.2 from 1.7.10 as a means to deal with ordered inputs coming to CEu assembly line.**

**Comment by GlodBlock** [comment]
fluid packet decoder is use to decode fluid packet instead of the drops:
![image](https://user-images.githubusercontent.com/60341015/190317529-02667661-ecc5-44ed-8b72-4b665e6c46b1.png)
drops is only used for display and don't have any actual use.
the interface will send the real fluid when doing fluid crafting jobs, you can check the wik about how to use them https://github.com/GlodBlock/AE2FluidCraft-Rework/wiki

**Comment by Synthitic** [comment]
My bad, I thought it turned drops into it's fluid. I was attempting a setup like [this](https://static.miraheze.org/gtnhwiki/thumb/c/c7/AE2FCAsslineproper.png/1920px-AE2FCAsslineproper.png) and could not get it to work, the system refused to push the craft into the subnet. I am not sure if it is because there is no "fluids first" button on 1.12.2.

**Comment by GlodBlock** [comment]
that setup is depend on sending fluid packet from normal me interface which is a 1.7.10 only feature so unfortunately you can't set up like that in 1.12.2.
also i am bit curious about why you need that setup since both gtce and gtceu's assembly line don't require ordered input like gt5u

**Comment by Synthitic** [comment]
CEu is adding ordered inputs with their assembly line research PR. I am using this setup on CE as I need a way to transfer the items instantly to the buses when crafting many items at a fast speed. The setup currently works perfectly except I do not have the fluids automated since the system just won't push the craft into the subnet. I thought fluid packets were able to be sent with a normal interface since if it a regular interface is attached to a machine that requires fluid, it pushes it fine. Does pushing into a subnet require a dual interface?

**Comment by GlodBlock** [comment]
well i will port these 1.7.10 features in 1.12 later

**Comment by GlodBlock** [comment]
> I thought fluid packets were able to be sent with a normal interface since if it a regular interface is attached to a machine that requires fluid, it pushes it fine. Does pushing into a subnet require a dual interface?

no that's just an intended design in 1.7.10. in 1.7.10 the normal interface will send fluid packet instead of real fluid by default, which can be turned off in config file. if it is turned off, the normal interface will send real fluid in pattern like what they do in 1.12. the dual interface is always sending the real fluid

**Comment by Synthitic** [comment]
Ok thanks, I got the setup working by changing out the p2ps and interfaces with dual interfaces and added fluid storage buses to the input hatches with priorities. The only thing that may go wrong is blocking mode not working properly. I will change the issue to adding the fluids first and fluid packet config for 1.12.2.

**Comment by GlodBlock** [comment]
added in 2.4.0 https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.0-r
you can click a button in interface gui to toggle fluid packet mode
