### ISSUE TITLE
An UI that can precisely modify the amount of fluid used when crafting

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#48]
Can you make an UI that can precisely modify the amount of fluid used when crafting (just like RS in 1.16)
It is much easier to modify the quantity than the original one, but it still could be by far conplicated in some occations.
(Would it be hard to code? I think it is a pity that AE2 don't have a method to modify the quantity of ingrediants by simply input a number, it can't even allow you to set more than 64 items in one slot.)
BTW, you did a really amazing job ,it is literally an exellent fantastic mod ngl.

添加一个像1.16RS的UI，可以通过输入一个精确的数字修改流体的量。
AE一个槽只能标记最多一组物品，真是太蠢了。

**Comment by GlodBlock** [comment]
in fact this feature is already implemented in 1.7.10's ae2fc. it won't be very hard to port this to 1.12.
![1](https://user-images.githubusercontent.com/60341015/192688394-c956d995-a3ef-4938-bbd1-537be77165e6.gif)
the problem is i am too busy with my rl stuff recently so i can't spare much time for modding.

**Comment by GlodBlock** [comment]
added in https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/e268d96c886e9f9e3d2f1eecdc6097777f366e8b
use 2.4.0 one

**Comment by YiRanMushroom** [comment]
Very awesome!
